### ISSUE TITLE
Uglify on Windows

### ISSUE THREAD

**Issue by danielfpedro** [markstory/asset_compress#314] opened 2018-02-08 21:30 UTC
```ini
cacheConfig = false
alwaysEnableController = false

[js]
timestamp = true
paths[] = WEBROOT/*
cachePath = WEBROOT/cache_js

[filter_Uglifyjs]
node = C:\Program Files\nodejs\node.exe
node_path = C:\xampp\htdocs\octopo-web-app\node_modules\uglify-js\bin\uglifyjs
uglify = C:\Users\figur\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs

[painel.default.js]
files[] = lib/jquery/dist/jquery.min.js
files[] = lib/jquery-ui/jquery-ui.min.js
files[] = lib/jquery-ui/ui/i18n/datepicker-pt-BR.js
files[] = lib/bootstrap/dist/js/bootstrap.min.js
files[] = lib/sweetalert2/dist/sweetalert2.min.js
files[] = lib/jquery.maskedinput/dist/jquery.maskedinput.min.js
files[] = lib/select2/dist/js/select2.full.min.js
files[] = js/plugins.js
files[] = js/painel/koletor.js

filters[] = Uglifyjs
```
### Error

```bash
2018-02-08 19:25:58 Error: [RuntimeException] ERROR: ENOENT: no such file or directory, open 'C:\xampp\htdocs\octopo-web-app\-'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at read_file (C:\Users\figur\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:322:19)
    at C:\Users\figur\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:156:37
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\figur\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:155:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) in C:\xampp\htdocs\octopo-web-app\vendor\markstory\mini-asset\src\Filter\AssetFilter.php on line 100
```

Looking to error trace we can figure that the issue is when will open the file but this part `C:\xampp\htdocs\octopo-web-app\-` says its trying open the file `-`.

**Comment by markstory** [comment] 2018-02-08 21:51
I don't have a way to test or reproduce issues on windows. You're going to have to figure this one out on your own.

**Comment by markstory** [comment] 2018-02-08 21:52
Duplicate of #286

**Closed by markstory** 2018-02-08 21:52 UTC
